### ISSUE TITLE
ELAN export

### ISSUE THREAD

**Issue by mr-martian** [mr-martian/rebabel-format#9]
Since e9a50496bc272c24ae6d3295f1351f14e18ab04d, `Writer` subclasses operate on query results, which is fine for formats with relatively limited semantics, but `.eaf` and a few other formats are flexible as to what hierarchy they represent and thus we need some way to building the appropriate query at run-time. I see three potential solutions:

### Option 1: Template files
We could accept a template file and derive the structure from that.

### Option 2: User supplies the query
The user could just write out the full query (though we would need to be careful not to screw up the internal machinery of `Writer`).

### Option 3: User supplies hierarchy
something like
```python
nodes = [
    ('phrase', None),
    ('word', 'phrase'),
    ('segment', 'word'),
]
```
indicating that we have phrases containing words containing segments.

**Comment by pandersity** [comment]
I am drawn to option one, because it has the potential to be the most accessible with less scripting experience. But definitely depends on the design of the template. Will the template be something created from scratch? Or something exported from ELAN and directly consumed by reBabel?

The less keystrokes a user has to type, the less likely they are to mess up internals or make mistakes. Makes it easier to succeed and find tool helpful.

**Comment by mr-martian** [comment]
> Will the template be something created from scratch by the user? Or something exported from ELAN and directly consumed by reBabel?

The implementation in [493228e](https://github.com/mr-martian/rebabel-format/commit/493228ed9096805913abc5a689ac3fc60ccb04ae) takes a normal EAF file and deletes any existing annotations.

**Comment by mr-martian** [comment]
Template files are sufficient for now, I think.
